/**
 * Build-time image optimization pipeline.
 *
 * Walks assets/images/ and, for every raster >= MIN_BYTES, emits AVIF + WebP
 * variants at standard widths (no upscaling) into assets/images/opt/,
 * mirroring the source directory structure:
 *
 *   assets/images/woku.png -> assets/images/opt/woku-480.avif, woku-480.webp, ...
 *
 * Also generates src/generated/imageManifest.ts so runtime code (ProjectGrid,
 * PhotoGallery) knows which images have variants and at which widths.
 *
 * Idempotent: a manifest of source mtimes (assets/images/opt/.cache.json)
 * skips already-processed files, so dev/CI builds stay fast.
 *
 * Runs before `vite build`; output is copied to dist/ by vite-plugin-static-copy.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'assets/images');
const OUT_DIR = path.join(SRC_DIR, 'opt');
const CACHE_FILE = path.join(OUT_DIR, '.cache.json');
const MANIFEST_TS = path.join(ROOT, 'src/generated/imageManifest.ts');

const WIDTHS = [480, 960, 1600];
const MIN_BYTES = 50 * 1024;
const RASTER_RE = /\.(png|jpe?g)$/i;

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (full === OUT_DIR) continue; // never re-process our own output
      files.push(...(await walk(full)));
    } else if (RASTER_RE.test(entry.name)) {
      files.push(full);
    }
  }
  return files;
}

async function loadCache() {
  try {
    return JSON.parse(await fs.readFile(CACHE_FILE, 'utf8'));
  } catch {
    return {};
  }
}

async function main() {
  const started = Date.now();
  await fs.mkdir(OUT_DIR, { recursive: true });
  const cache = await loadCache();
  const nextCache = {};
  // manifest: web path of original -> { w: available widths, width, height }
  const manifest = {};

  const files = await walk(SRC_DIR);
  let processed = 0;
  let skipped = 0;

  for (const file of files) {
    const rel = path.relative(SRC_DIR, file); // e.g. "woku.png" or "beyondTheCodePhotos/IMG_2178.JPG"
    const stat = await fs.stat(file);
    if (stat.size < MIN_BYTES) continue;

    const image = sharp(file, { failOn: 'none' });
    const meta = await image.metadata();
    if (!meta.width || !meta.height) continue;

    const widths = WIDTHS.filter((w) => w <= meta.width);
    // Include native width as the top step when it adds meaningful resolution
    // (also covers small-but-heavy images that match no standard width).
    const largest = widths[widths.length - 1] ?? 0;
    if (meta.width <= 1600 && meta.width > largest * 1.15) widths.push(meta.width);

    const base = rel.replace(/\.(png|jpe?g)$/i, '');
    const webPath = `/assets/images/${rel.split(path.sep).join('/')}`;
    manifest[webPath] = { widths, width: meta.width, height: meta.height };

    nextCache[rel] = stat.mtimeMs;
    if (cache[rel] === stat.mtimeMs) {
      skipped++;
      continue;
    }

    await fs.mkdir(path.dirname(path.join(OUT_DIR, rel)), { recursive: true });
    for (const w of widths) {
      const resized = sharp(file, { failOn: 'none' }).resize(w).rotate();
      const stem = path.join(OUT_DIR, `${base}-${w}`);
      await Promise.all([
        resized.clone().avif({ quality: 55 }).toFile(`${stem}.avif`),
        resized.clone().webp({ quality: 78 }).toFile(`${stem}.webp`)
      ]);
    }
    processed++;
  }

  await fs.writeFile(CACHE_FILE, JSON.stringify(nextCache, null, 2));

  const manifestSource = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.
// Maps original image web paths to their optimized variants in /assets/images/opt/.

export interface OptimizedImageEntry {
  widths: number[];
  width: number;
  height: number;
}

export const imageManifest: Record<string, OptimizedImageEntry> = ${JSON.stringify(
    manifest,
    null,
    2
  )};
`;
  await fs.mkdir(path.dirname(MANIFEST_TS), { recursive: true });
  await fs.writeFile(MANIFEST_TS, manifestSource);

  console.log(
    `optimize-images: ${processed} processed, ${skipped} cached, manifest entries: ${Object.keys(manifest).length} (${((Date.now() - started) / 1000).toFixed(1)}s)`
  );
}

main().catch((err) => {
  console.error('optimize-images failed:', err);
  process.exit(1);
});
